# Generated by Django 4.2.3 on 2023-07-04 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_value', models.FloatField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Баланс',
                'verbose_name_plural': 'Баланс',
            },
        ),
        migrations.CreateModel(
            name='WalletUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, verbose_name='Имя')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('balance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet_app.balance', verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_value', models.FloatField(default=0, verbose_name='Значение')),
                ('date', models.DateTimeField(editable=False, verbose_name='Дата')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet_app.walletuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
